/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.sql.PreparedStatement;
import java.sql.Statement;
import conexion.conexion;
import controlador.Ctrl_Partida;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Partida;
import modelo.TipoPartida;
import static vista.NewJInternalFrame_GestPartida.jTable_Partida;

/**
 *
 * @author LENOVO
 */
public class JInternalFrameAgregarPartida extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameAgregarPartida
     */
    int obtenerIdLibro = 0;
    int obtenerIdNpartida = 0;

    public JInternalFrameAgregarPartida() {
        initComponents();
        this.setSize(500, 440);
        this.setTitle("Agregar Partida");
        this.CargarComboLibros();
        this.CargarComboPartidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_num_partida = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellidoPat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_apellidoMat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_folio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_tipo_partidas = new javax.swing.JComboBox<>();
        btn_Guardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        combo_libros = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("AGREGAR PARTIDAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("N° DE PARTIDA");
        jLabel3.setAlignmentX(10.0F);
        jLabel3.setAlignmentY(1.0F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("NOMBRES:");
        jLabel4.setAlignmentX(10.0F);
        jLabel4.setAlignmentY(1.0F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        txt_num_partida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_num_partida.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(txt_num_partida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 210, -1));

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nombres.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("APELLIDO PATERNO:");
        jLabel5.setAlignmentX(10.0F);
        jLabel5.setAlignmentY(1.0F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, -1));

        txt_apellidoPat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_apellidoPat.setMinimumSize(new java.awt.Dimension(70, 25));
        txt_apellidoPat.setPreferredSize(new java.awt.Dimension(110, 30));
        txt_apellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoPatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("APELLIDO MATERNO:");
        jLabel6.setAlignmentX(10.0F);
        jLabel6.setAlignmentY(1.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        txt_apellidoMat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_apellidoMat.setMinimumSize(new java.awt.Dimension(70, 25));
        txt_apellidoMat.setName(""); // NOI18N
        txt_apellidoMat.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(txt_apellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("FOLIO:");
        jLabel7.setAlignmentX(10.0F);
        jLabel7.setAlignmentY(1.0F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, -1));

        txt_folio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_folio.setPreferredSize(new java.awt.Dimension(110, 30));
        txt_folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_folioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("TIPO DE PARTIDA:");
        jLabel8.setAlignmentX(10.0F);
        jLabel8.setAlignmentY(1.0F);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        combo_tipo_partidas.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        combo_tipo_partidas.setForeground(new java.awt.Color(102, 102, 102));
        combo_tipo_partidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo" }));
        combo_tipo_partidas.setMinimumSize(new java.awt.Dimension(124, 20));
        combo_tipo_partidas.setPreferredSize(new java.awt.Dimension(170, 30));
        combo_tipo_partidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipo_partidasActionPerformed(evt);
            }
        });
        getContentPane().add(combo_tipo_partidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        btn_Guardar.setBackground(new java.awt.Color(0, 153, 0));
        btn_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar.setText("GUARDAR");
        btn_Guardar.setPreferredSize(new java.awt.Dimension(95, 30));
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("LIBRO:");
        jLabel9.setAlignmentX(10.0F);
        jLabel9.setAlignmentY(1.0F);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        combo_libros.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        combo_libros.setForeground(new java.awt.Color(102, 102, 102));
        combo_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Libro" }));
        combo_libros.setMinimumSize(new java.awt.Dimension(124, 20));
        combo_libros.setPreferredSize(new java.awt.Dimension(170, 30));
        combo_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_librosActionPerformed(evt);
            }
        });
        getContentPane().add(combo_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wall2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoPatActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        Partida partida = new Partida();
        Ctrl_Partida controlPartida = new Ctrl_Partida();
        String libro = combo_libros.getSelectedItem().toString().trim();
        String TPartida = combo_tipo_partidas.getSelectedItem().toString().trim();
        // Validar campos
        if (txt_num_partida.getText().equals("") || txt_nombres.getText().equals("") || txt_apellidoPat.getText().equals("") || txt_apellidoMat.getText().equals("") || txt_folio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            txt_num_partida.setBackground(Color.red);
            txt_nombres.setBackground(Color.red);
            txt_apellidoPat.setBackground(Color.red);
            txt_apellidoMat.setBackground(Color.red);
            txt_folio.setBackground(Color.red);
        } else {
            // Consultar si la partida ya existe
            if (!controlPartida.existePartidaNum(txt_num_partida.getText().trim())) {
                if (libro.equalsIgnoreCase("Seleccionar Libro")) {
                    JOptionPane.showMessageDialog(null, "Seleccione Libro");
                }
                if (TPartida.equalsIgnoreCase("Seleccionar Tipo")) {
                    JOptionPane.showMessageDialog(null, "Seleccione Tipo de Partida");
                } else {
                    try {
                        partida.setN_partida(txt_num_partida.getText().trim().toUpperCase());
                        partida.setNombres(txt_nombres.getText().trim().toUpperCase());
                        partida.setApellido_pat(txt_apellidoPat.getText().trim().toUpperCase());
                        partida.setApellido_mat(txt_apellidoMat.getText().trim().toUpperCase());
                        partida.setFolio(txt_folio.getText().trim().toUpperCase());
                        partida.setId_Libro(IdLibro());
                        partida.setId_tipoPartida(IdnPartida());

                        if (controlPartida.guardar(partida)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            txt_num_partida.setBackground(Color.green);
                            txt_nombres.setBackground(Color.green);
                            txt_apellidoPat.setBackground(Color.green);
                            txt_apellidoMat.setBackground(Color.green);
                            txt_folio.setBackground(Color.green);
                            LimpiarCampos();

                            mostrarPartidas("Todos", jTable_Partida);

                            // Resto del código para limpiar y actualizar la interfaz
                            // this.CargarComboLibros();
                            // this.Limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                        }

                    } catch (Exception e) {
                        System.out.println("Error en: " + e);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El N°de partida ya existe en la Base de Datos");
            }
        }

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void combo_tipo_partidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipo_partidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipo_partidasActionPerformed

    private void txt_folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_folioActionPerformed

    private void combo_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_librosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox<String> combo_libros;
    private javax.swing.JComboBox<String> combo_tipo_partidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_apellidoMat;
    private javax.swing.JTextField txt_apellidoPat;
    private javax.swing.JTextField txt_folio;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_num_partida;
    // End of variables declaration//GEN-END:variables
private void CargarComboLibros() {
        Connection cn = conexion.conectar();
        String sql = "select * from libro order by cast(anio as unsigned)";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            combo_libros.removeAllItems();
            combo_libros.addItem("Seleccionar Libro");
            while (rs.next()) {
                combo_libros.addItem(rs.getString("anio"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar libros");
        }
    }

    private void CargarComboPartidas() {
        Connection cn = conexion.conectar();
        String sql = "select * from tipopartida order by cast(tipoPartida as unsigned)";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            combo_tipo_partidas.removeAllItems();
            combo_tipo_partidas.addItem("Seleccionar Tipo");
            while (rs.next()) {
                combo_tipo_partidas.addItem(rs.getString("tipoPartida"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al cargar tipo de partida");
        }
    }

    private int IdLibro() {
        if (combo_libros.getSelectedIndex() > 0) {
            String selectedLibroAnio = combo_libros.getSelectedItem().toString();
            obtenerIdLibro = getIdLibroFromAnio(selectedLibroAnio);
        } else {
            obtenerIdLibro = 0; // Otra acción por defecto, puedes ajustarla según tus necesidades
        }
        return obtenerIdLibro;
    }

    private int IdnPartida() {
        if (combo_tipo_partidas.getSelectedIndex() > 0) {
            String selectedPartidaN = combo_tipo_partidas.getSelectedItem().toString();
            obtenerIdNpartida = getIdTipoPartida(selectedPartidaN);
        } else {
            obtenerIdNpartida = 0; // Otra acción por defecto, puedes ajustarla según tus necesidades
        }
        return obtenerIdNpartida;
    }

    private void LimpiarCampos() {
        txt_num_partida.setText("");
        txt_nombres.setText("");
        txt_apellidoPat.setText("");
        txt_apellidoMat.setText("");
        txt_folio.setText("");
        CargarComboLibros();
        CargarComboPartidas();

        // Restablecer colores de fondo si es necesario
        txt_num_partida.setBackground(null);
        txt_nombres.setBackground(null);
        txt_apellidoPat.setBackground(null);
        txt_apellidoMat.setBackground(null);
        txt_folio.setBackground(null);
    }

    private int getIdLibroFromAnio(String anio) {
        int idLibro = 0;
        String sql = "SELECT id_Libro FROM libro WHERE anio = ?";

        try ( Connection cn = conexion.conectar();  PreparedStatement pst = cn.prepareStatement(sql)) {
            pst.setString(1, anio);

            try ( ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    idLibro = rs.getInt("id_Libro");
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener id Libro");
        }

        return idLibro;
    }

    private int getIdTipoPartida(String tipoPartida) {
        int idTipoPartida = 0;
        String sql = "SELECT id_tipoPartida FROM tipopartida WHERE tipoPartida = ?";

        try ( Connection cn = conexion.conectar();  PreparedStatement pst = cn.prepareStatement(sql)) {
            pst.setString(1, tipoPartida);

            try ( ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    idTipoPartida = rs.getInt("id_tipoPartida");
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener id Del Tipo de Partida");
        }

        return idTipoPartida;
    }

    public void mostrarPartidas(String selectedItem, JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); // Limpiar tabla antes de mostrar nuevos datos

        String tipoPartida = null;
        if (!selectedItem.equals("Todos")) {
            if (selectedItem.equals("Fallecimiento")) {
                tipoPartida = "Fallecimiento";
            } else if (selectedItem.equals("Nacimiento")) {
                tipoPartida = "Nacimiento";
            } else if (selectedItem.equals("Matrimonio")) {
                tipoPartida = "Matrimonio";
            }
        }

        String sql = "SELECT p.id_Partida, p.n_partida, p.nombres, p.apellido_pat, p.apellido_mat, p.folio, l.anio, t.tipoPartida "
                + "FROM partida p "
                + "JOIN libro l ON p.id_libro = l.id_libro "
                + "JOIN tipopartida t ON p.id_tipoPartida = t.id_tipoPartida ";

        if (tipoPartida != null) {
            sql += "WHERE t.tipoPartida = ?";
        }

        try ( Connection connection = conexion.conectar();  PreparedStatement statement = connection.prepareStatement(sql)) {
            if (tipoPartida != null) {
                statement.setString(1, tipoPartida);
            }
            try ( ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    Object[] row = new Object[]{
                        resultSet.getInt("id_Partida"),
                        resultSet.getString("n_partida"),
                        resultSet.getString("nombres"),
                        resultSet.getString("apellido_pat"),
                        resultSet.getString("apellido_mat"),
                        resultSet.getString("folio"),
                        resultSet.getString("anio"),
                        resultSet.getString("tipoPartida")
                    };
                    model.addRow(row);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al ejecutar la consulta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
