/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.sql.Statement;
import conexion.conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author LENOVO
 */
public class JInternalFrameAgregarPartida extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameAgregarPartida
     */
    public JInternalFrameAgregarPartida() {
        initComponents();
        this.setSize(450, 350);
        this.setTitle("Agregar Partida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellidoPat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_apellidoMat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_folio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_libros = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 102, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("AGREGAR PARTIDAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("NOMBRES:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        txt_dni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_dni.setPreferredSize(new java.awt.Dimension(70, 25));
        getContentPane().add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, -1));

        txt_nombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_nombres.setPreferredSize(new java.awt.Dimension(70, 25));
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("APELLIDO PATERNO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        txt_apellidoPat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_apellidoPat.setMinimumSize(new java.awt.Dimension(70, 25));
        txt_apellidoPat.setPreferredSize(new java.awt.Dimension(70, 25));
        txt_apellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoPatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("APELLIDO MATERNO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txt_apellidoMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_apellidoMat.setMinimumSize(new java.awt.Dimension(70, 25));
        txt_apellidoMat.setName(""); // NOI18N
        txt_apellidoMat.setPreferredSize(new java.awt.Dimension(70, 25));
        getContentPane().add(txt_apellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("FOLIO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 20));

        txt_folio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_folio.setPreferredSize(new java.awt.Dimension(70, 25));
        getContentPane().add(txt_folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("LIBRO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        combo_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Libro" }));
        combo_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_librosActionPerformed(evt);
            }
        });
        getContentPane().add(combo_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wall2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoPatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_librosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_libros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_apellidoMat;
    private javax.swing.JTextField txt_apellidoPat;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_folio;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
private void CargarComboLibros(){
Connection cn=conexion.conectar();
String sql ="select * from libros";
Statement st;
    try {
        st= cn.createStatement();
        ResultSet rs= st.executeQuery(sql);
        combo_libros.removeAllItems();
        
        
    } catch (SQLException e) {
        System.out.println("Error al cargar categoria");
    }
}

}
